class muscleName:
    short = [
        "AD-L",
        "AD-R",
        "BB-L",
        "BB-R",
        "BF-L",
        "BF-R",
        "BRD-L",
        "BRD-R",
        "ECRB-L",
        "ECRB-R",
        "ECRL-L",
        "ECRL-R",
        "ECU-L",
        "ECU-R",
        "ED-L",
        "ED-R",
        "EDM-L",
        "EDM-R",
        "EI-L",
        "EI-R",
        "EO-L",
        "EO-R",
        "FCR-L",
        "FCR-R",
        "FDP-L",
        "FDP-R",
        "FDS-L",
        "FDS-R",
        "FCU-L",
        "FCU-R",
        "FPL-L",
        "FPL-R",
        "GCL-L",
        "GCL-R",
        "GCM-L",
        "GCM-R",
        "GM-L",
        "GM-R",
        "Gme-L",
        "Gme-R",
        "IO-L",
        "IO-R",
        "ISP-L",
        "ISP-R",
        "LD-L",
        "LD-R",
        "LES-L",
        "LES-R",
        "LT-L",
        "LT-R",
        "MD-L",
        "MD-R",
        "MF-L",
        "MF-R",
        "MT-L",
        "MT-R",
        "PB-L",
        "PB-R",
        "PD-L",
        "PD-R",
        "PEL-L",
        "PEL-R",
        "PL-L",
        "PL-R",
        "PM-L",
        "PM-R",
        "RA-L",
        "RA-R",
        "RF-L",
        "RF-R",
        "SM-L",
        "SM-R",
        "SOL-L",
        "SOL-R",
        "SSP-L",
        "SSP-R",
        "SSC-L",
        "SSC-R",
        "ST-L",
        "ST-R",
        "TA-L",
        "TA-R",
        "TB-L",
        "TB-R",
        "TES-L",
        "TES-R",
        "TFL-L",
        "TFL-R",
        "TM-L",
        "TM-R",
        "UT-L",
        "UT-R",
        "VL-L",
        "VL-R",
        "VM-L",
        "VM-R",
        "VI-L",
        "VI-R",
    ]
    long = [
        "Deltoid (anterior)-L",
        "Deltoid (anterior)-R",
        "Biceps Brachii-L",
        "Biceps Brachii-R",
        "Biceps Femoris-L",
        "Biceps Femoris-R",
        "Brachioradialis-L",
        "Brachioradialis-R",
        "Extensor Carpi Radialis Brevis-L",
        "Extensor Carpi Radialis Brevis-R",
        "Extensor Carpi Radialis Longus-L",
        "Extensor Carpi Radialis Longus-R",
        "Extensor Carpi Ulnaris-L",
        "Extensor Carpi Ulnaris-R",
        "Extensor Digitorum-L",
        "Extensor Digitorum-R",
        "Extensor Digiti Minimi-L",
        "Extensor Digiti Minimi-R",
        "Extensor Indicis-L",
        "Extensor Indicis-R",
        "External Oblique-L",
        "External Oblique-R",
        "Flexor Carpi Radialis-L",
        "Flexor Carpi Radialis-R",
        "Flexor Digitorum Profundus-L",
        "Flexor Digitorum Profundus-R",
        "Flexor Digitorum Superficialis-L",
        "Flexor Digitorum Superficialis-R",
        "Flexor Carpi Ulnaris-L",
        "Flexor Carpi Ulnaris-R",
        "Flexor Pollicis Longus-L",
        "Flexor Pollicis Longus-R",
        "Gastrocnemius (lateral head)-L",
        "Gastrocnemius (lateral head)-R",
        "Gastrocnemius (medial head)-L",
        "Gastrocnemius (medial head)-R",
        "Gluteus Maximus-L",
        "Gluteus Maximus-R",
        "Gluteus Medius-L",
        "Gluteus Medius-R",
        "Internal Oblique-L",
        "Internal Oblique-R",
        "Infraspinatus-L",
        "Infraspinatus-R",
        "Latissimus Dorsi-L",
        "Latissimus Dorsi-R",
        "Lumbar Erector Spinae-L",
        "Lumbar Erector Spinae-R",
        "Trapezius (lower)-L",
        "Trapezius (lower)-R",
        "Deltoid (middle)-L",
        "Deltoid (middle)-R",
        "Multifidus-L",
        "Multifidus-R",
        "Trapezius (middle)-L",
        "Trapezius (middle)-R",
        "Peroneus Brevis-L",
        "Peroneus Brevis-R",
        "Deltoid (posterior)-L",
        "Deltoid (posterior)-R",
        "Peroneus Longus-L",
        "Peroneus Longus-R",
        "Palmaris Longus-L",
        "Palmaris Longus-R",
        "Pectoralis Major-L",
        "Pectoralis Major-R",
        "Rectus Abdominis-L",
        "Rectus Abdominis-R",
        "Rectus Femoris-L",
        "Rectus Femoris-R",
        "Semimembranosus-L",
        "Semimembranosus-R",
        "Soleus-L",
        "Soleus-R",
        "Supraspinatus-L",
        "Supraspinatus-R",
        "Subscapularis-L",
        "Subscapularis-R",
        "Semitendinosus-L",
        "Semitendinosus-R",
        "Tibialis Anterior-L",
        "Tibialis Anterior-R",
        "Triceps Brachii-L",
        "Triceps Brachii-R",
        "Thoracic Erector Spinae-L",
        "Thoracic Erector Spinae-R",
        "Tensor Fasciae Latae-L",
        "Tensor Fasciae Latae-R",
        "Teres Major-L",
        "Teres Major-R",
        "Trapezius (upper)-L",
        "Trapezius (upper)-R",
        "Vastus Lateralis-L",
        "Vastus Lateralis-R",
        "Vastus Medialis-L",
        "Vastus Medialis-R",
        "Vastus Intermedius-L",
        "Vastus Intermedius-R",
    ]

    def __getattr__(self, name):
        if name == "short":
            return self.short
        elif name == "long":
            return self.long

    def __getitem__(self, name):
        if name == "short":
            return self.short
        elif name == "long":
            return self.long

    @staticmethod
    def getLongName(n):
        if n in muscleName.short:
            return muscleName.long[muscleName.short.index(n)]
        elif n in muscleName.long:
            return n
        else:
            return ""

    @staticmethod
    def getShortName(n):
        if n in muscleName.long:
            return muscleName.short[muscleName.long.index(n)]
        elif n in muscleName.short:
            return n
        else:
            return ""

    @staticmethod
    def getConcatName(n):
        if n in muscleName.long:
            return "{} / {}".format(muscleName.short[muscleName.long.index(n)], n)
        elif n in muscleName.short:
            return "{} / {}".format(n, muscleName.long[muscleName.short.index(n)])
        else:
            return n
